import { createClient } from "@supabase/supabase-js";

const USER_ID = "db7d5dee-c813-40b6-a966-ebfacbee862d";

const stories = [
  { title: "Wipro Is Expanding a Productivity Tracker That Watches Word, Excel, Outlook and Chrome", source_url: "https://www.hrkatha.com/news/wipro-expands-employee-productivity-tracking-platform-across-india-2/", source_name: "HRKatha", published_at: "2026-09-04", category: "WORKPLACE ABSURDITY", score: 100, summary: "Wipro is expanding TimeScope from about 5,000 employees to a broader India workforce. Installed on company devices, it gives employees and managers dashboards of login duration and time spent in work applications including Word, Excel, PowerPoint, Outlook and Chrome.", strongest_comment: "Hank: ‘We’re measuring productivity.’ The squirrel: ‘By watching how long Excel is open? Excellent. I can leave Excel open.’", lesson: "When the proxy becomes the target, employees can optimize app-visible activity instead of outcomes. Measure completed work, quality and customer value rather than screen presence.", strongest_post_concept: "Strongest overall: THE PRODUCTIVITY DASHBOARD THAT MEASURES WHETHER EXCEL IS OPEN", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "The Trade Desk Cuts 15% of Staff to Build Smaller ‘Pods’ and ‘Scrums’", source_url: "https://www.exchange4media.com/media-others-news/the-trade-desk-cuts-global-workforce-by-15-in-restructuring-push-157946.html", source_name: "Exchange4media", published_at: "2026-09-04", category: "WORKPLACE ABSURDITY", score: 97, summary: "The Trade Desk is cutting about 15% of its global workforce while reorganizing employees into smaller teams. CEO Jeff Green said the restructuring is meant to improve agility and decision-making and is not being presented as a financial emergency.", strongest_comment: "Hank: ‘Why are 15% of people leaving?’ The squirrel: ‘So the remaining people can fit into smaller pods and scrums.’", lesson: "Reorganization is only simplification if it permanently removes handoffs, approvals and coordination overhead. Smaller boxes on the org chart do not automatically create simpler work.", strongest_post_concept: "WE CUT PEOPLE SO THE ORG CHART CAN HAVE SMALLER BOXES", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "BILL Goes Remote-First Because Commuting Is Time Employees Aren’t Serving Customers", source_url: "https://www.bill.com/blog/designing-the-future-of-work-at-bill", source_name: "BILL", published_at: "2026-09-03", category: "WORKPLACE ABSURDITY", score: 94, summary: "BILL is moving from a hybrid model to remote-first. Half of its workforce was already fully remote and the company says every minute saved from commuting is time employees can spend building, serving and supporting customers.", strongest_comment: "Hank: ‘Most companies are ordering people back.’ The squirrel: ‘BILL ran the commute through the productivity calculator first.’", lesson: "Workplace policy should be tied to the work that needs to happen, not to fashion. If a commute does not improve the outcome, it is reasonable to ask what value the requirement creates.", strongest_post_concept: "THE COMPANY THAT PUT THE COMMUTE ON THE PRODUCTIVITY DASHBOARD", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "Two Pigs Move Into a Detroit Neighborhood; Animal Control Catches One After an Hour-Long Chase", source_url: "https://www.upi.com/Odd_News/2026/09/03/detroit-pigs-one-captured/1901788457595/", source_name: "UPI", published_at: "2026-09-03", category: "OFF-THE-WALL ANIMALS", score: 100, summary: "Two pigs began roaming a Detroit neighborhood, letting residents pet them and accepting food from neighbors. Animal control spent more than an hour chasing the male before catching him in a bush; the female remained at large.", strongest_comment: "Hank: ‘Animal control caught the pig.’ The squirrel: ‘One pig. The second has retained outside counsel and remains remote.’", lesson: "A recurring exception needs a containment strategy, not repeated improvisation. Once the same problem keeps returning, treat it as a system issue.", strongest_post_concept: "THE NEIGHBORHOOD ACQUIRED TWO PIGS WITHOUT APPROVAL", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "A Sea Eagle With a Badly Broken Wing Is Still Flying Three Years Later", source_url: "https://news.stv.tv/highlands-islands/miracle-eagle-spotted-on-island-three-years-on-from-breaking-wing-in-near-fatal-fall", source_name: "STV News", published_at: "2026-09-04", category: "OFF-THE-WALL ANIMALS", score: 99, summary: "A white-tailed sea eagle nicknamed Kinky has been spotted flying over the Isle of Mull three years after a fall from its nest left it with a badly broken wing. Experts originally did not expect the bird to survive to adulthood.", strongest_comment: "Hank: ‘The experts didn’t think you’d make it.’ The squirrel: ‘The eagle apparently skipped that part of the project plan.’", lesson: "Forecasts are useful, but living systems can surprise us. Update the plan when reality proves more resilient than the assumption.", strongest_post_concept: "THE EAGLE THAT REFUSED THE PROJECTED OUTCOME", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "Mustang Finally Captured After Months Roaming Near a Maryland Reservoir", source_url: "https://www.cbsnews.com/baltimore/news/mustang-horse-loose-near-liberty-reservoir-captured-carroll-county/", source_name: "CBS Baltimore", published_at: "2026-09-03", category: "OFF-THE-WALL ANIMALS", score: 97, summary: "A mustang that had been roaming near Maryland’s Liberty Reservoir since late June was finally captured after months on the loose. Animal control worked with a professional horseman and a rescue, emphasizing patience rather than a fast pursuit.", strongest_comment: "Hank: ‘How did you finally catch the horse?’ The squirrel: ‘We stopped trying to make the horse cooperate with our timeline.’", lesson: "Some problems get harder when urgency turns into chasing. The better strategy can be patience, expertise and creating the conditions for a safe resolution.", strongest_post_concept: "THE TWO-MONTH TASK THAT GOT DONE WHEN EVERYONE STOPPED CHASING IT", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "Scientists Find a Black ‘Devil Flower’ That Lives Underground and Steals Food From Fungi", source_url: "https://www.sciencedaily.com/releases/2026/09/260903064217.htm", source_name: "ScienceDaily / Pensoft Publishers", published_at: "2026-09-03", category: "SQUIRREL DISTRACTION / WEIRD FACTS", score: 100, summary: "Botanists discovered Thismia daemona, a black horned flowering plant in Thailand that lacks chlorophyll, spends most of its life underground and gets nutrients through fungi instead of photosynthesis. Fewer than 50 individuals are known.", strongest_comment: "Hank: ‘It’s a plant.’ The squirrel: ‘It lives underground, has glowing-eye colors, steals from fungi and is called the devil flower. The meeting can wait.’", lesson: "Some facts earn attention because they overturn the category in your head. Curiosity is valuable when the anomaly is real, specific and testable.", strongest_post_concept: "THE PLANT THAT OPTED OUT OF BEING A NORMAL PLANT", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "Saturn Has Grown a Giant 10-Sided Pattern at Its South Pole", source_url: "https://www.sciencedaily.com/releases/2026/09/260903064229.htm", source_name: "ScienceDaily / NASA Goddard", published_at: "2026-09-03", category: "SQUIRREL DISTRACTION / WEIRD FACTS", score: 100, summary: "Hubble observations show a huge decagon-shaped atmospheric wave developing around Saturn’s south pole. The 10-sided pattern appears to have emerged only in the last few years and may be a southern counterpart to the planet’s famous northern hexagon.", strongest_comment: "Hank: ‘Saturn already had a hexagon.’ The squirrel: ‘Correct. It has now upgraded the other pole to a decagon.’", lesson: "Repeated observation matters because systems change. What was absent for decades can become obvious once conditions shift.", strongest_post_concept: "SATURN INSTALLED A SECOND GEOMETRY DEPARTMENT", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "A Dark Matter Detector Recorded One Event Scientists Can’t Explain", source_url: "https://www.sciencedaily.com/releases/2026/09/260904000313.htm", source_name: "ScienceDaily / Lawrence Berkeley National Laboratory", published_at: "2026-09-04", category: "SQUIRREL DISTRACTION / WEIRD FACTS", score: 99, summary: "The LUX-ZEPLIN dark matter experiment detected a rare particle interaction that is unusually difficult to explain as ordinary background noise and appeared where a dark-matter signal might be expected. Researchers stress that one event is not a discovery and more data are needed.", strongest_comment: "Hank: ‘Did we discover dark matter?’ The squirrel: ‘No. We discovered one thing that refuses to explain itself. I’m booked all afternoon.’", lesson: "An anomaly is a reason to investigate, not a reason to declare victory. Keep the curiosity high and the confidence proportional to the evidence.", strongest_post_concept: "ONE DOT ON THE CHART THAT RUINED EVERYONE’S AFTERNOON", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "87% Support Classroom Phone Restrictions — Yet Half of Parents Say Their Child Still Uses a Phone in Class", source_url: "https://educationnewscanada.com/article/education/level/k12/3/1216556/new-report-finds-87-of-canadians-back-classroom-cellphone-restrictions-but-in-class-use-continues.html", source_name: "Toronto Metropolitan University / Education News Canada", published_at: "2026-09-04", category: "PARENTING", score: 100, summary: "A national Canadian survey brief found record-high public support for classroom cellphone restrictions at 87%, while 50% of parents still report their child uses a phone in class during a typical school week. Full-day bell-to-bell policies were associated with higher confidence in enforcement and lower reported use.", strongest_comment: "Hank: ‘Phones are banned in class.’ The squirrel: ‘Excellent. Half the kids appear to have interpreted that as a mission statement rather than a rule.’", lesson: "A policy is only real when the environment, enforcement and expectations support it. Announcing the rule is not the same thing as changing the behavior.", strongest_post_concept: "THE PHONE BAN THAT HALF THE PHONES DIDN’T HEAR ABOUT", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "Students Are Less Excited About AI Than Their Parents and Teachers", source_url: "https://kvia.com/stacker-higher-ed/2026/09/04/ai-hype-fades-but-students-still-want-smarter-study-tools/", source_name: "KVIA / Stacker / Quizlet", published_at: "2026-09-04", category: "PARENTING", score: 95, summary: "Quizlet’s 2026 survey found teachers and parents were nearly twice as likely as students to view AI positively, 47% versus 25%, even though about 85% of high school and college students reported using AI for school assignments. Students were more interested in tools that adapt to their actual learning progress than in AI hype itself.", strongest_comment: "Hank: ‘The adults are more excited about AI in school than the students?’ The squirrel: ‘Apparently the kids would like the tool to help them learn before we finish the keynote.’", lesson: "Adoption is not enthusiasm and tool use is not proof of value. Ask the person doing the work what problem actually needs solving.", strongest_post_concept: "THE ADULTS ARE MORE EXCITED ABOUT THE KIDS’ AI THAN THE KIDS ARE", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "Companies Are Transforming So Fast Employees Don’t Have Time to Learn the Transformation", source_url: "https://en.prnasia.com/releases/apac/enterprise-transformation-is-underway-but-scaling-it-is-a-challenge-546328.shtml", source_name: "NTUC LearningHub / PR Newswire APAC", published_at: "2026-09-03", category: "OVERWHELMED", score: 100, summary: "NTUC LearningHub surveyed 450 working professionals and found 31% of employees said workload leaves too little time to learn and practice new ways of working, 30% said new ways of working add to existing demands, and 40% cited heavy workloads as a major impact of transformation.", strongest_comment: "Hank: ‘We need you to learn the new way of working.’ The squirrel: ‘Great. Which part of the old workload did we remove?’ Hank: ‘We did what now?’", lesson: "Transformation cannot be one more layer added to full capacity. If learning is required, organizations need to create time for learning and retire part of the old system.", strongest_post_concept: "PLEASE TRANSFORM — IN ADDITION TO EVERYTHING YOU ALREADY DO", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "84% of Parents Forget Something on the Back-to-School Checklist — 15% Say They’ve Cried From the Stress", source_url: "https://www.aol.co.uk/articles/back-school-checklist-shows-items-110856000.html", source_name: "AOL UK / Reach (Deliveroo-commissioned survey)", published_at: "2026-09-04", category: "OVERWHELMED", score: 99, summary: "A Deliveroo-commissioned back-to-school survey reports that 84% of parents have made an emergency shopping detour after forgetting an item and 15% say they have cried on the first day of school because of the stress. Water bottles, lunchboxes and PE kits top the forgotten-item list.", strongest_comment: "Hank: ‘We just need to get the kids to school.’ The squirrel arrives with a checklist, water bottle, lunchbox, PE kit, name labels, fidget toy, ice pack and tears: ‘Define just.’", lesson: "Life admin becomes overwhelming when dozens of tiny recurring requirements live in memory. Externalize the checklist and make the routine reusable instead of rebuilding it every morning.", strongest_post_concept: "THE FIRST DAY OF SCHOOL HAS 47 SUBTASKS", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "A Facebook Comment About One Odd Greek ‘O’ Turned Into New Research on a Ring Linked to Pilate", source_url: "https://phys.org/news/2026-09-unusual-greek-mystery-pontius-pilate.html", source_name: "Phys.org / UCLA", published_at: "2026-09-02", category: "RABBIT HOLES WITH A GOOD END", score: 100, summary: "UCLA scholar Catherine Bonesho noticed a discussion of an odd Greek spelling on a 2,000-year-old ring linked to the administration of Pilate and commented on Facebook that it might actually be Latin written in Greek letters. That small observation grew into a published reinterpretation of who likely used the ring and what the inscription meant.", strongest_comment: "Hank: ‘You left a Facebook comment about one letter?’ The squirrel: ‘Yes. It became a paper about Roman administration.’", lesson: "Sometimes the squirrel should win. A productive rabbit hole starts when a small anomaly is specific enough to test and someone follows it with real scholarship instead of just another comment thread.", strongest_post_concept: "THE FACEBOOK COMMENT THAT BECAME A RESEARCH PAPER", post_type: "multi_pane_cartoon", panel_count: 4 },
  { title: "Scientists Swab Medieval Gospels and Reconstruct 3,500 Years of a Livestock Virus", source_url: "https://phys.org/news/2026-09-hidden-dna-medieval-gospels-reveals.html", source_name: "Phys.org / University College Dublin", published_at: "2026-09-02", category: "RABBIT HOLES WITH A GOOD END", score: 100, summary: "Researchers extracted ancient DNA from the animal-skin parchment of historic manuscripts including the York Gospels and found traces of sheeppox virus. The work helped reconstruct roughly 3,500 years of the pathogen’s evolution and showed that old books can double as biological archives of livestock disease.", strongest_comment: "Hank: ‘You’re studying a thousand-year-old gospel.’ The squirrel: ‘Correct. It is also a veterinary records system.’", lesson: "Old artifacts can answer entirely new questions when better tools arrive. The useful detour is recognizing that an object can contain information far beyond the purpose for which it was created.", strongest_post_concept: "THE MEDIEVAL BOOK THAT TURNED OUT TO BE A DISEASE DATABASE", post_type: "multi_pane_cartoon", panel_count: 4 }
];

export async function GET(request: Request) {
  const secret = process.env.CRON_SECRET;
  if (!secret || request.headers.get("authorization") !== `Bearer ${secret}`) return Response.json({ error: "Unauthorized" }, { status: 401 });

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SECRET_KEY;
  if (!url || !key) return Response.json({ error: "Supabase server credentials unavailable" }, { status: 503 });
  const supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });

  const results: Array<Record<string, unknown>> = [];
  for (const story of stories) {
    const { data, error } = await supabase.rpc("ingest_hank_news_updates", { p_user_id: USER_ID, p_stories: [story] });
    if (error) {
      const row = { title: story.title, result: "failed", reason: error.message };
      results.push(row);
      console.error("HANK_NEWS_2026_09_04_ROW", JSON.stringify(row));
      continue;
    }
    const row = Array.isArray(data) && data.length ? data[0] as Record<string, unknown> : { title: story.title, result: "failed", reason: "No explicit function result" };
    results.push(row);
    console.log("HANK_NEWS_2026_09_04_ROW", JSON.stringify(row));
  }

  const ids = results.map((row) => String(row.content_item_id ?? "")).filter(Boolean);
  const { data: verified, error: verifyError } = ids.length
    ? await supabase.from("content_items").select("id,identifier,title,status,content_type,panel_count,score").in("id", ids).order("identifier")
    : { data: [], error: null };
  for (const row of verified ?? []) console.log("HANK_NEWS_2026_09_04_VERIFY", JSON.stringify(row));
  if (verifyError) console.error("HANK_NEWS_2026_09_04_VERIFY_ERROR", verifyError.message);

  return Response.json({ count: results.length, results, verified: verified ?? [], verify_error: verifyError?.message ?? null });
}
